/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.uci.ics.gamendo1.service.idm;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {


}
